<?php

namespace app\models\medis;

use Yii;
use app\models\pegawai\TbPegawai;
use app\models\pendaftaran\Layanan;

/**
 * This is the model class for table "medis.tarif_tindakan_pasien".
 *
 * @property int $id
 * @property int $tarif_tindakan_id reff medis.tarif_tindakan.id
 * @property int $layanan_id reff pendaftaran.layanan.id
 * @property int|null $dokter_id reff pegawai.tb_pegawai.pegawai_id, jika dokter yg melakukan
 * @property int|null $perawat_id reff pegawai.tb_pegawai.pegawai_id, jika perawat yg melakukan
 * @property int $cyto
 * @property string|null $keterangan
 * @property string $created_at
 * @property int $created_by
 * @property string|null $updated_at
 * @property int|null $updated_by
 * @property int $is_deleted
 */
class TarifTindakanPasien extends BaseModelAR
{
  /**
   * {@inheritdoc}
   */
  public static function tableName()
  {
    return 'medis.tarif_tindakan_pasien';
  }

  /**
   * {@inheritdoc}
   */
  public function rules()
  {
    return [
      [['tarif_tindakan_id', 'layanan_id', 'cyto', 'jumlah'], 'required'],
      [['pelaksana_id', 'layanan_id', 'cyto', 'created_by', 'updated_by', 'is_deleted', 'jumlah', 'harga', 'subtotal', 'jenis_tindakan'], 'integer'],
      ['jumlah', 'integer', 'min' => 1],
      [['keterangan'], 'string'],
      [['created_at', 'updated_at'], 'safe'],
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function attributeLabels()
  {
    return [
      'id' => 'ID',
      'tarif_tindakan_id' => 'Tindakan',
      'tanggal' => 'Tanggal',
      'pelaksana_id' => 'Dokter',
      'layanan_id' => 'Unit',
      'cyto' => 'Cyto',
      'jumlah' => 'Jumlah',
      'keterangan' => 'Keterangan',
      'created_at' => 'Created At',
      'created_by' => 'Created By',
      'updated_at' => 'Updated At',
      'updated_by' => 'Updated By',
      'is_deleted' => 'Is Deleted',
    ];
  }
  public function beforeSave($insert)
  {
    if ($insert) {
      $this->tanggal = date('Y-m-d H:i:s');
      $this->is_deleted = 0;
    }
    return parent::beforeSave($insert); // TODO: Change the autogenerated stub
  }
  function setDelete($user_id)
  {
    $this->is_deleted = 1;
    $this->updated_at = date('Y-m-d H:i:s');
    $this->updated_by = $user_id;
  }
  /**
   * {@inheritdoc}
   * @return TarifTindakanPasienQuery the active query used by this AR class.
   */
  public static function find()
  {
    return new TarifTindakanPasienQuery(get_called_class());
  }
  function getTarifTindakan()
  {
    return $this->hasOne(TarifTindakan::className(), ['id' => 'tarif_tindakan_id']);
  }
  function getPelaksana()
  {
    return $this->hasOne(TbPegawai::className(), ['pegawai_id' => 'pelaksana_id']);
  }
  function getLayanan()
  {
    return $this->hasOne(Layanan::className(), ['id' => 'layanan_id']);
  }
}
